# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0358220527e4ee21f16c4314466e9e096eb9c40dfe4e003da8bb7f98ef25aa312a899ec0bb2dee45a06cf8d5cfe3e1355f90c92ccf72d3c8e727c542337ee624

test:
  secret_key_base: 136b37677649f968ff6b843094615ab82748052bf0d050c92c57fee7e05d3941310711ffed065e1fd424eac795e36f9c7fc7720d0586b5381205355bf20b3f51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
